import { ContractorProjectDetail } from '../types/contractor';

export const INITIAL_CONTRACTOR_PROJECTS: ContractorProjectDetail[] = [
  {
    id: 'proj-1',
    clientCode: 'CLT-8842',
    projectName: 'Skyline Penthouse Renovation',
    clientName: 'Vikramaditya Singhania',
    clientPhone: '+91 98201 12345',
    siteAddress: 'Flat 4201, Tower B, Worli Sea Face, Mumbai',
    startDate: '15 Sep 2026',
    status: 'active',
    contractorId: null,
    clientId: null,
    scopeItems: [
      {
        id: 'sc-1',
        name: 'Italian Marble Flooring & Skirting',
        unit: 'sqft',
        quantity: 1850,
        ratePerUnit: 145,
        totalAmount: 268250,
        completedQuantity: 1200,
      },
      {
        id: 'sc-2',
        name: 'POP False Ceiling with Cove Profiles',
        unit: 'sqft',
        quantity: 1600,
        ratePerUnit: 85,
        totalAmount: 136000,
        completedQuantity: 950,
      },
      {
        id: 'sc-3',
        name: 'Heavy Concealed Electrical Conduiting',
        unit: 'rft',
        quantity: 2400,
        ratePerUnit: 48,
        totalAmount: 115200,
        completedQuantity: 2100,
      },
      {
        id: 'sc-4',
        name: 'Bathroom Waterproofing & Epoxy Grouting',
        unit: 'sqft',
        quantity: 450,
        ratePerUnit: 120,
        totalAmount: 54000,
        completedQuantity: 450,
      },
      {
        id: 'sc-5',
        name: 'Royal Luxury Wall Emulsion & Primer',
        unit: 'sqft',
        quantity: 4200,
        ratePerUnit: 35,
        totalAmount: 147000,
        completedQuantity: 1800,
      },
    ],
    workers: [
      {
        id: 'w-1',
        name: 'Rameshwar Yadav',
        role: 'Mason',
        dailyWage: 950,
        phone: '+91 98111 22334',
      },
      {
        id: 'w-2',
        name: 'Mohammad Shamim',
        role: 'Electrician',
        dailyWage: 1100,
        phone: '+91 98222 33445',
      },
      {
        id: 'w-3',
        name: 'Santosh Kumar',
        role: 'Helper',
        dailyWage: 650,
        phone: '+91 98333 44556',
      },
      {
        id: 'w-4',
        name: 'Ganesh Shinde',
        role: 'Painter',
        dailyWage: 900,
        phone: '+91 98444 55667',
      },
      {
        id: 'w-5',
        name: 'Babu Lal',
        role: 'Helper',
        dailyWage: 650,
        phone: '+91 98555 66778',
      },
    ],
    todayAttendance: [
      {
        workerId: 'w-1',
        workerName: 'Rameshwar Yadav',
        role: 'Mason',
        dailyWage: 950,
        date: 'Today',
        status: 'present',
        checkInTime: '08:42 AM',
        proofVerified: true,
        proofNote: 'Site Gate Selfie & GPS on-time verified ✓',
        wageCalculated: 950,
      },
      {
        workerId: 'w-2',
        workerName: 'Mohammad Shamim',
        role: 'Electrician',
        dailyWage: 1100,
        date: 'Today',
        status: 'present',
        checkInTime: '08:50 AM',
        proofVerified: true,
        proofNote: 'Site Gate Selfie & GPS on-time verified ✓',
        wageCalculated: 1100,
      },
      {
        workerId: 'w-3',
        workerName: 'Santosh Kumar',
        role: 'Helper',
        dailyWage: 650,
        date: 'Today',
        status: 'present',
        checkInTime: '08:45 AM',
        proofVerified: true,
        proofNote: 'Tool inventory sign-in verified ✓',
        wageCalculated: 650,
      },
      {
        workerId: 'w-4',
        workerName: 'Ganesh Shinde',
        role: 'Painter',
        dailyWage: 900,
        date: 'Today',
        status: 'absent',
        checkInTime: '—',
        proofVerified: false,
        proofNote: 'Informed sick leave',
        wageCalculated: 0,
      },
      {
        workerId: 'w-5',
        workerName: 'Babu Lal',
        role: 'Helper',
        dailyWage: 650,
        date: 'Today',
        status: 'half_day',
        checkInTime: '01:15 PM',
        proofVerified: true,
        proofNote: 'Afternoon cement offload shift verified ✓',
        wageCalculated: 325,
      },
    ],
    dailyReports: [
      {
        id: 'rep-yesterday',
        date: 'Yesterday, 01 Oct 2026',
        verifiedBy: 'Contractor In-Person',
        items: [
          {
            scopeItemId: 'sc-1',
            name: 'Italian Marble Flooring',
            unit: 'sqft',
            qtyDoneToday: 180,
            ratePerUnit: 145,
            totalValueToday: 26100,
          },
          {
            scopeItemId: 'sc-3',
            name: 'Concealed Conduiting',
            unit: 'rft',
            qtyDoneToday: 220,
            ratePerUnit: 48,
            totalValueToday: 10560,
          },
        ],
        totalWorkValueToday: 36660,
        totalWorkerWageToday: 3650,
        contractorMarginToday: 33010,
        isVerified: true,
      },
    ],
    transactions: [
      {
        id: 'tx-1',
        date: '16 Sep 2026',
        amount: 250000,
        type: 'received_from_client',
        note: 'Project Mobilization Advance',
        recipientOrPayer: 'Client: Vikramaditya Singhania',
        referenceNo: 'HDFC-RTGS-99021',
      },
      {
        id: 'tx-2',
        date: '25 Sep 2026',
        amount: 175000,
        type: 'received_from_client',
        note: 'Stage 1 Milestone Sign-off (Flooring)',
        recipientOrPayer: 'Client: Vikramaditya Singhania',
        referenceNo: 'IMPS-20260925-1104',
      },
      {
        id: 'tx-3',
        date: '20 Sep 2026',
        amount: 32400,
        type: 'paid_to_worker',
        note: 'Weekly Labor Wage Disbursement (5 workers)',
        recipientOrPayer: 'Workforce Crew Payroll',
        referenceNo: 'UPI-WAGE-9921',
      },
      {
        id: 'tx-4',
        date: '27 Sep 2026',
        amount: 38200,
        type: 'paid_to_worker',
        note: 'Weekly Labor Wage Disbursement (5 workers)',
        recipientOrPayer: 'Workforce Crew Payroll',
        referenceNo: 'UPI-WAGE-9954',
      },
    ],
    chatState: {
      workerMessagingAllowed: false,
      messages: [
        {
          id: 'msg-1',
          senderRole: 'client',
          senderName: 'Vikramaditya Singhania',
          content: 'Good morning team. How is the master bedroom Italian marble progress coming along today?',
          timestamp: '09:15 AM',
        },
        {
          id: 'msg-2',
          senderRole: 'contractor',
          senderName: 'Apex Contractors (You)',
          content: 'Good morning sir! Rameshwar and crew have laid 150 sqft already. Skirting will be completed by 4 PM. We will verify and generate the daily bill this evening.',
          timestamp: '09:22 AM',
        },
        {
          id: 'msg-3',
          senderRole: 'contractor',
          senderName: 'Apex Contractors (You)',
          content: '🔒 Worker messaging authority is currently restricted by contractor.',
          timestamp: '09:23 AM',
          isAuthorityAction: true,
        },
      ],
    },
  },
  {
    id: 'proj-2',
    clientCode: 'CLT-5510',
    projectName: 'Corporate Office Fitout & HVAC',
    clientName: 'Apex Business Solutions',
    clientPhone: '+91 98202 23456',
    siteAddress: 'Unit 802, Godrej One, Vikhroli, Mumbai',
    startDate: '22 Sep 2026',
    status: 'active',
    contractorId: null,
    clientId: null,
    scopeItems: [
      {
        id: 'sc-21',
        name: 'Glass Partition Modular Framing',
        unit: 'rft',
        quantity: 480,
        ratePerUnit: 180,
        totalAmount: 86400,
        completedQuantity: 240,
      },
      {
        id: 'sc-22',
        name: 'Acoustic Ceiling Tiles',
        unit: 'sqft',
        quantity: 3200,
        ratePerUnit: 65,
        totalAmount: 208000,
        completedQuantity: 1800,
      },
    ],
    workers: [
      {
        id: 'w-21',
        name: 'Deepak Varma',
        role: 'Carpenter',
        dailyWage: 1000,
        phone: '+91 98666 77889',
      },
      {
        id: 'w-22',
        name: 'Kallu Ram',
        role: 'Helper',
        dailyWage: 650,
        phone: '+91 98777 88990',
      },
    ],
    todayAttendance: [
      {
        workerId: 'w-21',
        workerName: 'Deepak Varma',
        role: 'Carpenter',
        dailyWage: 1000,
        date: 'Today',
        status: 'present',
        checkInTime: '08:35 AM',
        proofVerified: true,
        proofNote: 'Security biometric on-time verified ✓',
        wageCalculated: 1000,
      },
      {
        workerId: 'w-22',
        workerName: 'Kallu Ram',
        role: 'Helper',
        dailyWage: 650,
        date: 'Today',
        status: 'present',
        checkInTime: '08:40 AM',
        proofVerified: true,
        proofNote: 'Security biometric on-time verified ✓',
        wageCalculated: 650,
      },
    ],
    dailyReports: [],
    transactions: [
      {
        id: 'tx-21',
        date: '23 Sep 2026',
        amount: 150000,
        type: 'received_from_client',
        note: 'Contract Advance',
        recipientOrPayer: 'Client: Apex Business Solutions',
        referenceNo: 'NEFT-CORP-4482',
      },
    ],
    chatState: {
      workerMessagingAllowed: true,
      messages: [
        {
          id: 'msg-201',
          senderRole: 'contractor',
          senderName: 'Apex Contractors (You)',
          content: 'All workers are verified on site for HVAC partition fitout. Deepak, please share acoustic framing status.',
          timestamp: '09:00 AM',
        },
        {
          id: 'msg-202',
          senderRole: 'contractor',
          senderName: 'Apex Contractors (You)',
          content: '🔓 Contractor granted messaging authority to workers for technical updates.',
          timestamp: '09:01 AM',
          isAuthorityAction: true,
        },
        {
          id: 'msg-203',
          senderRole: 'worker',
          senderName: 'Deepak Varma (Carpenter)',
          content: 'Sir, framing grid is ready for inspection. 12 acoustic panels installed on north wall.',
          timestamp: '09:30 AM',
        },
      ],
    },
  },
  {
    id: 'proj-3',
    clientCode: 'CLT-9104',
    projectName: 'Bandra Retail Showroom Fitout',
    clientName: 'Karan Mehra',
    clientPhone: '+91 98333 77889',
    siteAddress: 'Ground Floor, Linking Road, Bandra West, Mumbai',
    startDate: '10 Oct 2026',
    status: 'upcoming',
    contractorId: null,
    clientId: null,
    scopeItems: [
      {
        id: 'sc-31',
        name: 'Storefront Toughened Glass Glazing',
        unit: 'sqft',
        quantity: 600,
        ratePerUnit: 220,
        totalAmount: 132000,
        completedQuantity: 0,
      },
      {
        id: 'sc-32',
        name: 'Spot Lighting & Track Fixture Wiring',
        unit: 'nos',
        quantity: 48,
        ratePerUnit: 850,
        totalAmount: 40800,
        completedQuantity: 0,
      },
    ],
    workers: [],
    todayAttendance: [],
    dailyReports: [],
    transactions: [],
  },
];
