// Autogenerated Servex Logo particle definitions sampled directly from assets/servex_logo.png
export interface LogoParticle {
  id: number;
  targetX: number; // Normalized target X (-0.5 to 0.5)
  targetY: number; // Normalized target Y (-0.5 to 0.5)
  scatterX: number; // Initial scatter offset X
  scatterY: number; // Initial scatter offset Y
  size: number;
  color: string;
  delay: number; // Stagger ms
  brightness?: number;
}

export const LOGO_PARTICLES: LogoParticle[] = [
  {
    "id": 0,
    "targetX": -0.314,
    "targetY": -0.434,
    "scatterX": 0.932,
    "scatterY": -0.812,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 67,
    "brightness": 255
  },
  {
    "id": 1,
    "targetX": -0.263,
    "targetY": -0.467,
    "scatterX": -0.188,
    "scatterY": -1.019,
    "size": 3.6,
    "color": "#3B82F6",
    "delay": 85,
    "brightness": 255
  },
  {
    "id": 2,
    "targetX": -0.103,
    "targetY": -0.491,
    "scatterX": -0.507,
    "scatterY": 1.051,
    "size": 4,
    "color": "#FFFFFF",
    "delay": 107,
    "brightness": 253
  },
  {
    "id": 3,
    "targetX": -0.061,
    "targetY": -0.488,
    "scatterX": 0.255,
    "scatterY": 0.567,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 20,
    "brightness": 255
  },
  {
    "id": 4,
    "targetX": 0.011,
    "targetY": -0.392,
    "scatterX": -0.729,
    "scatterY": 0.28,
    "size": 3.5,
    "color": "#FFFFFF",
    "delay": 5,
    "brightness": 255
  },
  {
    "id": 5,
    "targetX": -0.402,
    "targetY": -0.266,
    "scatterX": -1.133,
    "scatterY": -0.338,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 15,
    "brightness": 254
  },
  {
    "id": 6,
    "targetX": -0.36,
    "targetY": -0.374,
    "scatterX": 0.772,
    "scatterY": -0.514,
    "size": 2.7,
    "color": "#3B82F6",
    "delay": 41,
    "brightness": 255
  },
  {
    "id": 7,
    "targetX": -0.207,
    "targetY": -0.309,
    "scatterX": 0.062,
    "scatterY": -0.753,
    "size": 2.7,
    "color": "#3B82F6",
    "delay": 79,
    "brightness": 238
  },
  {
    "id": 8,
    "targetX": -0.12,
    "targetY": -0.311,
    "scatterX": 0.728,
    "scatterY": -0.268,
    "size": 2.5,
    "color": "#FFFFFF",
    "delay": 8,
    "brightness": 253
  },
  {
    "id": 9,
    "targetX": -0.025,
    "targetY": -0.372,
    "scatterX": -1.048,
    "scatterY": 0.592,
    "size": 3,
    "color": "#FFFFFF",
    "delay": 59,
    "brightness": 255
  },
  {
    "id": 10,
    "targetX": 0.008,
    "targetY": -0.374,
    "scatterX": 0.761,
    "scatterY": 1.114,
    "size": 2.9,
    "color": "#FFFFFF",
    "delay": 64,
    "brightness": 255
  },
  {
    "id": 11,
    "targetX": 0.29,
    "targetY": -0.275,
    "scatterX": -1.117,
    "scatterY": -0.472,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 118,
    "brightness": 255
  },
  {
    "id": 12,
    "targetX": 0.332,
    "targetY": -0.303,
    "scatterX": -1.037,
    "scatterY": 0.245,
    "size": 3.4,
    "color": "#FFFFFF",
    "delay": 69,
    "brightness": 255
  },
  {
    "id": 13,
    "targetX": 0.411,
    "targetY": -0.301,
    "scatterX": 0.351,
    "scatterY": 0.876,
    "size": 3.1,
    "color": "#60A5FA",
    "delay": 45,
    "brightness": 255
  },
  {
    "id": 14,
    "targetX": -0.402,
    "targetY": -0.245,
    "scatterX": -0.221,
    "scatterY": 1.343,
    "size": 3,
    "color": "#60A5FA",
    "delay": 60,
    "brightness": 255
  },
  {
    "id": 15,
    "targetX": -0.356,
    "targetY": -0.247,
    "scatterX": -0.597,
    "scatterY": -0.307,
    "size": 3.6,
    "color": "#60A5FA",
    "delay": 34,
    "brightness": 255
  },
  {
    "id": 16,
    "targetX": -0.294,
    "targetY": -0.209,
    "scatterX": -0.857,
    "scatterY": 0.461,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 108,
    "brightness": 255
  },
  {
    "id": 17,
    "targetX": -0.183,
    "targetY": -0.127,
    "scatterX": 0.593,
    "scatterY": 0.22,
    "size": 3.2,
    "color": "#FFFFFF",
    "delay": 91,
    "brightness": 254
  },
  {
    "id": 18,
    "targetX": -0.003,
    "targetY": -0.214,
    "scatterX": 0.42,
    "scatterY": 0.481,
    "size": 3.2,
    "color": "#3B82F6",
    "delay": 66,
    "brightness": 214
  },
  {
    "id": 19,
    "targetX": 0.067,
    "targetY": -0.174,
    "scatterX": 0.475,
    "scatterY": -1.229,
    "size": 3.2,
    "color": "#FFFFFF",
    "delay": 99,
    "brightness": 253
  },
  {
    "id": 20,
    "targetX": 0.174,
    "targetY": -0.152,
    "scatterX": -0.676,
    "scatterY": -0.263,
    "size": 3.9,
    "color": "#FFFFFF",
    "delay": 66,
    "brightness": 248
  },
  {
    "id": 21,
    "targetX": 0.266,
    "targetY": -0.244,
    "scatterX": 0.24,
    "scatterY": -0.552,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 61,
    "brightness": 255
  },
  {
    "id": 22,
    "targetX": 0.392,
    "targetY": -0.242,
    "scatterX": -0.963,
    "scatterY": 0.745,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 54,
    "brightness": 255
  },
  {
    "id": 23,
    "targetX": 0.429,
    "targetY": -0.247,
    "scatterX": -0.532,
    "scatterY": -0.607,
    "size": 3.2,
    "color": "#60A5FA",
    "delay": 20,
    "brightness": 255
  },
  {
    "id": 24,
    "targetX": -0.363,
    "targetY": -0.122,
    "scatterX": -0.741,
    "scatterY": -0.88,
    "size": 3,
    "color": "#60A5FA",
    "delay": 25,
    "brightness": 255
  },
  {
    "id": 25,
    "targetX": -0.286,
    "targetY": -0.117,
    "scatterX": 0.787,
    "scatterY": -1.016,
    "size": 3.4,
    "color": "#60A5FA",
    "delay": 109,
    "brightness": 255
  },
  {
    "id": 26,
    "targetX": -0.163,
    "targetY": -0.112,
    "scatterX": -0.453,
    "scatterY": -0.412,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 85,
    "brightness": 253
  },
  {
    "id": 27,
    "targetX": -0.077,
    "targetY": -0.068,
    "scatterX": -0.594,
    "scatterY": -0.43,
    "size": 2.8,
    "color": "#FFFFFF",
    "delay": 69,
    "brightness": 251
  },
  {
    "id": 28,
    "targetX": 0.07,
    "targetY": -0.055,
    "scatterX": 0.668,
    "scatterY": -0.813,
    "size": 2.7,
    "color": "#60A5FA",
    "delay": 35,
    "brightness": 252
  },
  {
    "id": 29,
    "targetX": 0.116,
    "targetY": -0.089,
    "scatterX": -0.719,
    "scatterY": 0.237,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 49,
    "brightness": 255
  },
  {
    "id": 30,
    "targetX": 0.296,
    "targetY": -0.092,
    "scatterX": 0.28,
    "scatterY": 1.194,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 98,
    "brightness": 248
  },
  {
    "id": 31,
    "targetX": 0.339,
    "targetY": -0.111,
    "scatterX": -0.455,
    "scatterY": 1.019,
    "size": 3.9,
    "color": "#FFFFFF",
    "delay": 35,
    "brightness": 252
  },
  {
    "id": 32,
    "targetX": -0.316,
    "targetY": 0.005,
    "scatterX": -0.613,
    "scatterY": -0.324,
    "size": 3.3,
    "color": "#60A5FA",
    "delay": 40,
    "brightness": 254
  },
  {
    "id": 33,
    "targetX": -0.258,
    "targetY": 0.046,
    "scatterX": -0.831,
    "scatterY": 0.328,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 25,
    "brightness": 253
  },
  {
    "id": 34,
    "targetX": -0.168,
    "targetY": 0.098,
    "scatterX": -0.01,
    "scatterY": 1.164,
    "size": 3.5,
    "color": "#FFFFFF",
    "delay": 71,
    "brightness": 252
  },
  {
    "id": 35,
    "targetX": -0.088,
    "targetY": 0.003,
    "scatterX": 0.406,
    "scatterY": 0.742,
    "size": 2.7,
    "color": "#FFFFFF",
    "delay": 84,
    "brightness": 242
  },
  {
    "id": 36,
    "targetX": 0.094,
    "targetY": 0.009,
    "scatterX": 0.321,
    "scatterY": -1.164,
    "size": 3,
    "color": "#3B82F6",
    "delay": 108,
    "brightness": 253
  },
  {
    "id": 37,
    "targetX": 0.166,
    "targetY": 0.019,
    "scatterX": 0.065,
    "scatterY": -0.851,
    "size": 3.3,
    "color": "#FFFFFF",
    "delay": 28,
    "brightness": 255
  },
  {
    "id": 38,
    "targetX": 0.21,
    "targetY": 0.051,
    "scatterX": -0.746,
    "scatterY": -1.003,
    "size": 3,
    "color": "#FFFFFF",
    "delay": 114,
    "brightness": 255
  },
  {
    "id": 39,
    "targetX": -0.109,
    "targetY": 0.131,
    "scatterX": 0.662,
    "scatterY": 0.35,
    "size": 3.9,
    "color": "#FFFFFF",
    "delay": 85,
    "brightness": 245
  },
  {
    "id": 40,
    "targetX": -0.064,
    "targetY": 0.158,
    "scatterX": -0.637,
    "scatterY": 0.336,
    "size": 3.2,
    "color": "#3B82F6",
    "delay": 109,
    "brightness": 251
  },
  {
    "id": 41,
    "targetX": 0.005,
    "targetY": 0.212,
    "scatterX": -0.276,
    "scatterY": 0.489,
    "size": 4,
    "color": "#FFFFFF",
    "delay": 47,
    "brightness": 236
  },
  {
    "id": 42,
    "targetX": 0.157,
    "targetY": 0.152,
    "scatterX": -0.218,
    "scatterY": 0.459,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 96,
    "brightness": 255
  },
  {
    "id": 43,
    "targetX": 0.256,
    "targetY": 0.127,
    "scatterX": 0.719,
    "scatterY": -0.213,
    "size": 2.4,
    "color": "#FFFFFF",
    "delay": 30,
    "brightness": 255
  },
  {
    "id": 44,
    "targetX": 0.306,
    "targetY": 0.2,
    "scatterX": -0.711,
    "scatterY": 0.637,
    "size": 3.7,
    "color": "#60A5FA",
    "delay": 33,
    "brightness": 253
  },
  {
    "id": 45,
    "targetX": -0.401,
    "targetY": 0.371,
    "scatterX": 0.771,
    "scatterY": 0.339,
    "size": 3.4,
    "color": "#3B82F6",
    "delay": 22,
    "brightness": 254
  },
  {
    "id": 46,
    "targetX": -0.329,
    "targetY": 0.322,
    "scatterX": 0.537,
    "scatterY": 1.208,
    "size": 2.5,
    "color": "#FFFFFF",
    "delay": 86,
    "brightness": 255
  },
  {
    "id": 47,
    "targetX": -0.297,
    "targetY": 0.322,
    "scatterX": -0.187,
    "scatterY": 0.53,
    "size": 2.8,
    "color": "#FFFFFF",
    "delay": 71,
    "brightness": 254
  },
  {
    "id": 48,
    "targetX": -0.196,
    "targetY": 0.322,
    "scatterX": -1.367,
    "scatterY": 0.119,
    "size": 3.9,
    "color": "#60A5FA",
    "delay": 106,
    "brightness": 253
  },
  {
    "id": 49,
    "targetX": -0.1,
    "targetY": 0.352,
    "scatterX": 0.027,
    "scatterY": 0.962,
    "size": 3.7,
    "color": "#FFFFFF",
    "delay": 19,
    "brightness": 212
  },
  {
    "id": 50,
    "targetX": 0.069,
    "targetY": 0.361,
    "scatterX": -0.108,
    "scatterY": 0.789,
    "size": 3.5,
    "color": "#FFFFFF",
    "delay": 34,
    "brightness": 245
  },
  {
    "id": 51,
    "targetX": 0.168,
    "targetY": 0.264,
    "scatterX": -0.083,
    "scatterY": 0.582,
    "size": 3.9,
    "color": "#3B82F6",
    "delay": 12,
    "brightness": 252
  },
  {
    "id": 52,
    "targetX": 0.222,
    "targetY": 0.331,
    "scatterX": -0.908,
    "scatterY": -0.66,
    "size": 3.6,
    "color": "#FFFFFF",
    "delay": 83,
    "brightness": 250
  },
  {
    "id": 53,
    "targetX": 0.363,
    "targetY": 0.285,
    "scatterX": -0.81,
    "scatterY": -0.45,
    "size": 3.8,
    "color": "#FFFFFF",
    "delay": 19,
    "brightness": 250
  },
  {
    "id": 54,
    "targetX": 0.411,
    "targetY": 0.358,
    "scatterX": 0.198,
    "scatterY": 0.506,
    "size": 3.2,
    "color": "#FFFFFF",
    "delay": 68,
    "brightness": 237
  },
  {
    "id": 55,
    "targetX": -0.403,
    "targetY": 0.38,
    "scatterX": 0.979,
    "scatterY": 0.712,
    "size": 2.7,
    "color": "#FFFFFF",
    "delay": 50,
    "brightness": 255
  },
  {
    "id": 56,
    "targetX": -0.396,
    "targetY": 0.394,
    "scatterX": -0.204,
    "scatterY": 1.315,
    "size": 2.9,
    "color": "#FFFFFF",
    "delay": 85,
    "brightness": 255
  },
  {
    "id": 57,
    "targetX": -0.294,
    "targetY": 0.484,
    "scatterX": -0.679,
    "scatterY": 0.368,
    "size": 3.4,
    "color": "#FFFFFF",
    "delay": 88,
    "brightness": 254
  },
  {
    "id": 58,
    "targetX": -0.198,
    "targetY": 0.485,
    "scatterX": 1.039,
    "scatterY": 0.733,
    "size": 3.3,
    "color": "#FFFFFF",
    "delay": 64,
    "brightness": 250
  },
  {
    "id": 59,
    "targetX": -0.012,
    "targetY": 0.479,
    "scatterX": -1.132,
    "scatterY": 0.045,
    "size": 2.4,
    "color": "#3B82F6",
    "delay": 104,
    "brightness": 254
  },
  {
    "id": 60,
    "targetX": 0.016,
    "targetY": 0.463,
    "scatterX": 1.093,
    "scatterY": -0.645,
    "size": 3.5,
    "color": "#FFFFFF",
    "delay": 81,
    "brightness": 251
  },
  {
    "id": 61,
    "targetX": 0.242,
    "targetY": 0.387,
    "scatterX": 0.788,
    "scatterY": -0.105,
    "size": 2.6,
    "color": "#FFFFFF",
    "delay": 39,
    "brightness": 240
  },
  {
    "id": 62,
    "targetX": 0.303,
    "targetY": 0.377,
    "scatterX": 0.536,
    "scatterY": -0.403,
    "size": 3.4,
    "color": "#60A5FA",
    "delay": 116,
    "brightness": 233
  },
  {
    "id": 63,
    "targetX": 0.435,
    "targetY": 0.397,
    "scatterX": 1.251,
    "scatterY": -0.016,
    "size": 3.9,
    "color": "#FFFFFF",
    "delay": 28,
    "brightness": 233
  }
];
