const fs = require('fs');
const zlib = require('zlib');

const buf = fs.readFileSync('assets/servex_logo.png');

let pos = 8;
let width = 0, height = 0, bitDepth = 0, colorType = 0;
const idatChunks = [];

while (pos < buf.length) {
  const len = buf.readUInt32BE(pos);
  const type = buf.slice(pos + 4, pos + 8).toString('ascii');
  if (type === 'IHDR') {
    width = buf.readUInt32BE(pos + 8);
    height = buf.readUInt32BE(pos + 12);
    bitDepth = buf[pos + 16];
    colorType = buf[pos + 17];
  } else if (type === 'IDAT') {
    idatChunks.push(buf.slice(pos + 8, pos + 8 + len));
  } else if (type === 'IEND') {
    break;
  }
  pos += 12 + len;
}

const decompressed = zlib.inflateSync(Buffer.concat(idatChunks));
const bpp = 4;
const lineLen = 1 + width * bpp;
const img = Buffer.alloc(width * height * bpp);

for (let y = 0; y < height; y++) {
  for (let i = 0; i < width * bpp; i++) {
    const rawVal = decompressed[y * lineLen + 1 + i];
    const upVal = y > 0 ? img[(y - 1) * width * bpp + i] : 0;
    img[y * width * bpp + i] = (rawVal + upVal) & 0xff;
  }
}

const points = [];
for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const idx = (y * width + x) * bpp;
    const r = img[idx];
    const g = img[idx + 1];
    const b = img[idx + 2];
    const brightness = (r + g + b) / 3;
    if (brightness > 90) {
      points.push({ x, y, brightness });
    }
  }
}

const minX = 196;
const maxX = 821;
const minY = 263;
const maxY = 701;
const logoW = maxX - minX;
const logoH = maxY - minY;

// Grid sampling: 10 cols x 8 rows to target ~50-60 points
const gridCols = 10;
const gridRows = 8;
const cellW = logoW / gridCols;
const cellH = logoH / gridRows;

const sampled = [];
let seed = 42;
function pseudoRandom() {
  seed = (seed * 9301 + 49297) % 233280;
  return seed / 233280;
}

for (let r = 0; r < gridRows; r++) {
  for (let c = 0; c < gridCols; c++) {
    const cx1 = minX + c * cellW;
    const cx2 = cx1 + cellW;
    const cy1 = minY + r * cellH;
    const cy2 = cy1 + cellH;

    const cellPoints = points.filter(p => p.x >= cx1 && p.x < cx2 && p.y >= cy1 && p.y < cy2);
    if (cellPoints.length > 8) {
      cellPoints.sort((a, b) => b.brightness - a.brightness);
      // Average top 5 points
      const topPts = cellPoints.slice(0, Math.min(5, cellPoints.length));
      const avgX = topPts.reduce((acc, p) => acc + p.x, 0) / topPts.length;
      const avgY = topPts.reduce((acc, p) => acc + p.y, 0) / topPts.length;
      const avgBrightness = topPts.reduce((acc, p) => acc + p.brightness, 0) / topPts.length;

      // Normalized coordinates: center at 0,0, range -0.5 to 0.5 horizontally and vertically
      const normX = (avgX - (minX + maxX) / 2) / logoW;
      const normY = (avgY - (minY + maxY) / 2) / logoH;

      // Subtle initial scatter offset: distributed around center, within ~1.5x logo width/height
      // With angle & radius
      const scatterAngle = pseudoRandom() * Math.PI * 2;
      const scatterDist = 0.5 + pseudoRandom() * 0.9;
      const initScatterX = Math.cos(scatterAngle) * scatterDist;
      const initScatterY = Math.sin(scatterAngle) * scatterDist;

      // Restrained color tones: predominantly #FFFFFF, with 20% deep/ocean blue accent #60A5FA / #3B82F6
      const isBlueAccent = pseudoRandom() < 0.22;
      const color = isBlueAccent ? (pseudoRandom() < 0.5 ? '#60A5FA' : '#3B82F6') : '#FFFFFF';

      const size = Number((2.4 + pseudoRandom() * 1.6).toFixed(1)); // 2.4 - 4.0 dp
      const delay = Math.round(pseudoRandom() * 120); // 0 - 120ms stagger

      sampled.push({
        id: sampled.length,
        targetX: Number(normX.toFixed(3)),
        targetY: Number(normY.toFixed(3)),
        scatterX: Number(initScatterX.toFixed(3)),
        scatterY: Number(initScatterY.toFixed(3)),
        size,
        color,
        delay,
        brightness: Math.round(avgBrightness),
      });
    }
  }
}

console.log('Total sampled points:', sampled.length);

const asciiGrid = Array.from({ length: 14 }, () => Array(28).fill(' '));
for (const p of sampled) {
  const ax = Math.round((p.targetX + 0.5) * 26);
  const ay = Math.round((p.targetY + 0.5) * 12);
  if (ay >= 0 && ay < 14 && ax >= 0 && ax < 28) {
    asciiGrid[ay][ax] = '●';
  }
}
console.log('\nASCII PREVIEW (~' + sampled.length + ' particles):\n');
console.log(asciiGrid.map(row => row.join('')).join('\n'));

// Generate TypeScript code
const tsCode = `// Autogenerated Servex Logo particle definitions sampled directly from assets/servex_logo.png
export interface LogoParticle {
  id: number;
  targetX: number; // Normalized target X (-0.5 to 0.5)
  targetY: number; // Normalized target Y (-0.5 to 0.5)
  scatterX: number; // Initial scatter offset X
  scatterY: number; // Initial scatter offset Y
  size: number;
  color: string;
  delay: number; // Stagger ms
}

export const LOGO_PARTICLES: LogoParticle[] = ${JSON.stringify(sampled, null, 2)};
`;

fs.writeFileSync('src/components/logoParticlesData.ts', tsCode);
console.log('Successfully wrote src/components/logoParticlesData.ts');
